/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @see       http://buildwithcraft.com
 @package   craft.app.resources
*/
(function(a){Craft.UpdateInfo=Garnish.Base.extend({appUpdateInfo:null,$container:null,$downloadBtn:null,licenseHud:null,$licenseSubmitBtn:null,licenseSubmitAction:null,allowAutoUpdates:null,init:function(){var b=a("#graphic"),d=a("#status");Craft.postActionRequest("update/getAvailableUpdates",a.proxy(function(c,f){if("success"!=f||c.error||c.errors){var e=Craft.t("An unknown error occurred.");c.errors&&c.errors.length?e=c.errors[0]:c.error&&(e=c.error);b.addClass("error");d.text(e)}else e={total:c.app&&
c.app.releases&&c.app.releases.length?1:0,critical:c.app&&c.criticalUpdateAvailable},e.total?(b.velocity("fadeOut",{duration:"fast"}),d.fadeOut("fast",a.proxy(function(){b.remove();d.remove();this.appUpdateInfo=c.app;this.allowAutoUpdates=c.allowAutoUpdates;this.showAvailableUpdates()},this))):(b.addClass("success"),d.text(Craft.t("You\u2019re all up-to-date!"))),Craft.cp.displayUpdateInfo(e)},this))},showAvailableUpdates:function(){this.$container=a("<div/>").appendTo(Craft.cp.$main).hide();var b=
a('<div class="pane clearafter"/>').appendTo(this.$container);a('<h2 class="heading">'+Craft.t("You\u2019ve got updates!")+"</h2>").appendTo(b);b=a('<div class="buttons"/>').appendTo(b);if(!this.allowAutoUpdates||this.appUpdateInfo.manualUpdateRequired)this.$downloadBtn=a('<div class="btn submit">'+Craft.t("Download")+"</div>").appendTo(b);else{var d=a('<div class="btngroup submit"/>').appendTo(b),c=a('<div class="btn submit">'+Craft.t("Update")+"</div>").appendTo(d),b=a('<div class="btn submit menubtn"/>').appendTo(d),
d=a('<div class="menu" data-align="right"/>').appendTo(d),d=a("<ul/>").appendTo(d),d=a("<li/>").appendTo(d);this.$downloadBtn=a("<a>"+Craft.t("Download")+"</a>").appendTo(d);new Garnish.MenuBtn(b)}this.allowAutoUpdates&&(this.appUpdateInfo.licenseUpdated?(this.addListener(this.$downloadBtn,"click","showLicenseForm"),this.appUpdateInfo.manualUpdateRequired||this.addListener(c,"click","showLicenseForm")):(this.addListener(this.$downloadBtn,"click","downloadThat"),this.appUpdateInfo.manualUpdateRequired||
this.addListener(c,"click","autoUpdateThat")));this.showReleases(this.appUpdateInfo.releases,"Craft");this.$container.velocity("fadeIn",{duration:"fast"})},showLicenseForm:function(b){b.stopPropagation();if(this.licenseHud)this.licenseHud.$trigger=a(b.currentTarget),this.licenseHud.show();else{var d=a("<form><p>"+Craft.t('Craft\u2019s <a href="http://buildwithcraft.com/license" target="_blank">Terms and Conditions</a> have changed.')+"</p></form>"),c=a("<label> "+Craft.t("I agree.")+" &nbsp;</label>").appendTo(d),
f=a('<input type="checkbox"/>').prependTo(c);this.$licenseSubmitBtn=a('<input class="btn submit" type="submit"/>').appendTo(d);this.licenseHud=new Garnish.HUD(b.currentTarget,d);this.addListener(d,"submit",function(a){a.preventDefault();f.prop("checked")?(this.licenseSubmitAction(),this.licenseHud.hide(),f.prop("checked",!1)):Garnish.shake(this.licenseHud.$hud)})}b.currentTarget==this.$downloadBtn[0]?(this.$licenseSubmitBtn.attr("value",Craft.t("Seriously, download.")),this.licenseSubmitAction=this.downloadThat):
(this.$licenseSubmitBtn.attr("value",Craft.t("Seriously, update.")),this.licenseSubmitAction=this.autoUpdateThat)},showReleases:function(b,d){for(var c=0;c<b.length;c++){var f=a('<div class="pane release"/>').appendTo(this.$container),e=b[c],g=d+" "+e.version;e.build&&(g+=' <span class="light">'+Craft.t("build {build}",{build:e.build})+"</span>");e.critical&&(g+=' <span class="critical">'+Craft.t("Critical")+"</span>");a("<h2>"+g+"</h2>").appendTo(f);a('<div class="notes"/>').appendTo(f).html(e.notes)}},
downloadThat:function(){var b=this.appUpdateInfo.manualDownloadEndpoint;"https:"==window.location.protocol&&(b=b.replace("http:","https:"));a("<iframe/>",{src:b}).appendTo(Garnish.$bod).hide()},autoUpdateThat:function(){window.location.href=Craft.getUrl("updates/go/craft")}})})(jQuery);

//# sourceMappingURL=updates.min.map
